# Generated by scripts/brew-formula.sh in reearth/ezu — do not edit.
class Ezu < Formula
  desc "Command-line renderer for the Ezu Style Spec"
  homepage "https://github.com/reearth/ezu"
  version "0.11.0"
  license any_of: ["MIT", "Apache-2.0"]

  on_macos do
    on_arm do
      url "https://github.com/reearth/ezu/releases/download/v0.11.0/ezu-v0.11.0-aarch64-apple-darwin.tar.gz"
      sha256 "ced74e72c0265b2371d85487b6d090df84a0570703001848cfb85ac24b91c815"
    end
    on_intel do
      url "https://github.com/reearth/ezu/releases/download/v0.11.0/ezu-v0.11.0-x86_64-apple-darwin.tar.gz"
      sha256 "abc4cfa42b1b06867b56d90ff6cfcb768037202905df95cfd9e0ced8e8147d69"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/reearth/ezu/releases/download/v0.11.0/ezu-v0.11.0-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "4f1d9305397b98a3ac2ef570e4a88326f94cffe2eafabddf35b38e713eefefff"
    end
    on_intel do
      url "https://github.com/reearth/ezu/releases/download/v0.11.0/ezu-v0.11.0-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "64f21f381908b6d7087657f9963d9a9a75628be3a13374f2d34b945f6c470c9f"
    end
  end

  def install
    bin.install "ezu"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/ezu --version")
  end
end
